services:
  app:
    container_name: strava-ride-insights-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NODE_ENV=development
      - TZ=Europe/Madrid
      - APP_SECRET=replace_with_secure_random_string_at_least_32_chars
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
