services:
  app:
    container_name: strava-ride-insights
    image: ghcr.io/hi-otto/strava-ride-insights:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - TZ=Europe/Madrid
      - APP_SECRET=replace_with_secure_random_string_at_least_32_chars
    restart: always
